[package]
name = "witness-studio-app"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
egg = "0.9"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
warp = "0.3"
rust-embed = { version = "8", features = ["compression", "interpolate-folder-path"] }
